const spectatingLists = {
  "@cto56 既 acc1": [
    "牙拉: @LaplusDarknesss",
    "中岡: @NKOK_15",
    "牙沙: @sakamatachloe",
    "牙風: @kazamairohach",
    "35: @sakuramiko35",
    "牙船: @houshoumarine",
    "牙衰: @suisei_hosimati",
    "Lamy: @yukihanalamy",
    "mmssnn: @momosuzunene",
    "ばばなつみ: @b723_chan",
    "牙猩: @amanekanatach",
    "牙鬼: @nakiriayame",
    "牙夸: @minatoaqua",
    "みけねこ: @95rn16",
    "利香: @kuroneko_datenn",
    "羽衣媽媽: @ui_shig",
    "1000000: @1000000lome",
    "Space通知bot: @holo_space_bot",
  ],
  "@cto56 既 acc2": ["直播時間表通知bot: @hololive_notify"],
  "@ykhnlm 既 acc": [
    "牙狗: @inugamikorone",
    "Mumei: @nanashimumei_en",
    "Kronii: @ourokronii",
    "Fauna: @ceresfauna",
    "Ame: @watsonameliaEN",
    "牙ru: @uruharushia",
    "IRyS: @irys_en",
    "牙星: @Sara_Hoshikawa",
    "牙星裏垢: @Hoshikawa_sub",
    "戌亥とこ: @inui_toko",
    "rurudo: @rurudo_",
    "rurudo日常: @LION_desuwa",
    "郡道: @g9v9g_mirei",
    "郡道中之人: @g6mo2",
    "古打拿: @whatweneed8837",
  ],
};

module.exports = { spectatingLists };
