const stickersList = [
  "35: https://t.me/addstickers/Miko_Youtube_Stickers",
  "牙衰: https://t.me/addstickers/SuiseiStickers",
  "ロボ子: https://t.me/addstickers/RobocoSan",
  "FBK: https://t.me/addstickers/shirakamiFubukiStickers",
  "Mel: https://t.me/addstickers/YozoraMelStickers",
  "牙哈: https://t.me/addstickers/AkaiHaatoStickers",
  "牙夸: https://t.me/addstickers/AquaStickers",
  "牙紫: https://t.me/addstickers/MurasakiShionStickers",
  "牙鬼: https://t.me/addstickers/AyameStickers",
  "Choco: https://t.me/addstickers/ChocoSenSeiStickers",
  "牙狗: https://t.me/addstickers/InugamiKoroneStickers",
  "牙狼: https://t.me/addstickers/ookamimioStickers",
  "牙船: https://t.me/addstickers/MarineStickers",
  "Pekora: https://t.me/addstickers/PekoraStickers",
  "牙火: https://t.me/addstickers/ShiranuiFlareStickers",
  "牙ru: https://t.me/addstickers/RushiaStickers",
  "牙猩: https://t.me/addstickers/PJKStickers",
  "牙羊: https://t.me/addstickers/WatameStickers",
  "んああああ: https://t.me/addstickers/HimemoriLunaStickers",
  "Lamy: https://t.me/addstickers/LamyStickers",
  "mmssnn: https://t.me/addstickers/NeneYoutubeStickers",
  "牙拉: https://t.me/addstickers/LaplusStickers",
  "牙沙: https://t.me/addstickers/SakamataStickers",
  "牙風: https://t.me/addstickers/kazamaYoutubeSticker",
  "牙博: https://t.me/addstickers/KoyoriStickers",
  "Gura: https://t.me/addstickers/GawrGuraYoutubeStickers",
  "IRyS https://t.me/addstickers/IRySStickers",
  "Mumei: https://t.me/addstickers/MumeiStickers",
  "Kronii: https://t.me/addstickers/KroniiStickers",
  "Bae: https://t.me/addstickers/BaelzStickers",
  "Koseki Bijou: https://t.me/addstickers/KosekiBijou_by_moe_sticker_bot",
  "HololiveYoutube: https://t.me/addstickers/hololive_youtube_stickers",
  "HoloEarth: https://t.me/addstickers/HoloEarthStickers",
  "Hololive Sticker Vol.1: https://t.me/addstickers/holostickerVol1",
  "Hololive Sticker Vol.2: https://t.me/addstickers/holostickerVol2",
  "Hololive そらちゃん: https://t.me/addstickers/tokino_sora",
  "Hololive AZKi: https://t.me/addstickers/line247387489a24_by_moe_sticker_bot",
  "Hololive ロボ子: https://t.me/addstickers/robocoLineStickers",
  "Hololive メル: https://t.me/addstickers/YozoraMelLine",
  "Hololive FBK Vol.2: https://t.me/addstickers/FubukiLineStickersVol2",
  "Hololive 牙星: https://t.me/addstickers/line248951729e74_by_moe_sticker_bot",
  "Hololive 牙夸: https://t.me/addstickers/hololiveStickerAqua",
  "Hololive 486: https://t.me/addstickers/line249037790cf5_by_moe_sticker_bot",
  "Hololive 牙鬼: https://t.me/addstickers/line23278776e54e_by_moe_sticker_bot",
  "Hololive 牙狼: https://t.me/addstickers/mioLineStickers",
  "Hololive 牙貓: https://t.me/addstickers/OkayuLineStamps",
  "Hololive 牙船: https://t.me/addstickers/houshou_marine",
  "Hololive 牙船2: https://t.me/addstickers/line23836214c7e6_by_moe_sticker_bot",
  "Hololive 牙火: https://t.me/addstickers/FlareLineStickers",
  "Hololive 牙團: https://t.me/addstickers/ShiroganeNoelStickers",
  "Hololive 牙羊: https://t.me/addstickers/WatameLineStamps",
  "Hololive 牙拖: https://t.me/addstickers/towa_line",
  "Hololive mmsznn: https://t.me/addstickers/NeneLineStickers",
  "Hololive 菈米: https://t.me/addstickers/LamyLineStickers",
  "Hololive 菈米2: https://t.me/addstickers/line271611552db0_by_moe_sticker_bot",
  "Hololive 牙囡: https://t.me/addstickers/TakaneruiLineStickers",
  "Hololive 牙博: https://t.me/addstickers/KoyoriLineStickers",
  "Hololive バカタレ: https://t.me/addstickers/bakatare",
  "Hololive 火建: https://t.me/addstickers/line24885949c77c_by_moe_sticker_bot",
  "Hololive AquaMarine: https://t.me/addstickers/line249595080847_by_moe_sticker_bot",
  "Hololive Sweet Happy Holiday: https://t.me/addstickers/line25144321bc88_by_moe_sticker_bot",
  "Hololive 3期生: https://t.me/addstickers/line25468988e8e8_by_moe_sticker_bot",
  "ソニころ: https://t.me/addstickers/sonic_korone",
  "壱百満天原サロメ: https://t.me/addstickers/line2666287645b8_by_moe_sticker_bot",
  "星川: https://t.me/addstickers/hoshikawa_sara_by_moe_sticker_bot",
  "郡道: https://t.me/addstickers/mirei_line_stickers1",
  "阿咩咩: https://t.me/addstickers/amamiya_animated_stickers",
  "阿咩咩2: https://t.me/addstickers/line20860557ad2f_by_moe_sticker_bot",
  "るんちょま: https://t.me/addstickers/line290163916720_by_moe_sticker_bot",
  "える: https://t.me/addstickers/line256591931816_by_moe_sticker_bot",
  "Petit: https://t.me/addstickers/ratna_petit",
  "羽衣媽媽: https://t.me/addstickers/UiShigStickers",
  "Rurudo: https://t.me/addstickers/rurudo",
  "結城さくな: https://t.me/addstickers/yuki_sakuna_by_moe_sticker_bot",
  "橘ひなの: https://t.me/addstickers/HinanoStickers",
  "橘ひなの Twitch: https://t.me/addstickers/hinano_twitch_by_moe_sticker_bot",
  "花芽すみれ: https://t.me/addstickers/KagaSumire",
  "花芽すみれ Twitch: https://t.me/addstickers/kagasumire_by_moe_sticker_bot",
  "花芽なずな: https://t.me/addstickers/KagaNazuna",
  "兎咲ミミ: https://t.me/addstickers/TosakiStickers",
  "英リサ: https://t.me/addstickers/HanabusaStickers",
  "八雲べに: https://t.me/addstickers/YakumoBeniStickers",
  "紫宮るな: https://t.me/addstickers/shinomiyaStickers",
  "夢野あかり: https://t.me/addstickers/akarinStickers_by_moe_sticker_bot",
  "夢野あかり2: https://t.me/addstickers/akarinStickers2_by_moe_sticker_bot",
  "紡木こかげ: https://t.me/addstickers/Kokage_Tsumugi_by_moe_sticker_bot",
  "千燈ゆうひ: https://t.me/addstickers/SendoYuuhi_by_moe_sticker_bot",
  "千燈ゆうひ Twitch: https://t.me/addstickers/sendo_yuuhi_by_moe_sticker_bot",
  "甘結もか: https://t.me/addstickers/Moka_Amayui_by_moe_sticker_bot",
  "花芽すみれ日常スタンプ: https://t.me/addstickers/line30491084e507_by_moe_sticker_bot",
  "一ノ瀬うるは日常スタンプ: https://t.me/addstickers/line30491189520f_by_moe_sticker_bot",
  "空澄セナ日常スタンプ: https://t.me/addstickers/line304912083e09_by_moe_sticker_bot",
  "藍沢エマ日常スタンプ: https://t.me/addstickers/line30491223e47f_by_moe_sticker_bot",
  "甘結もか日常スタンプ: https://t.me/addstickers/line30523791dced_by_moe_sticker_bot",
  "花芽なずな日常スタンプ: https://t.me/addstickers/line3064008817c5_by_moe_sticker_bot",
  "小雀とと日常スタンプ: https://t.me/addstickers/line306400842f67_by_moe_sticker_bot",
  "胡桃のあ日常スタンプ: https://t.me/addstickers/line30640075f6f2_by_moe_sticker_bot",
  "如月れん日常スタンプ: https://t.me/addstickers/line30640308b82c_by_moe_sticker_bot",
  "神成きゅぴ日常スタンプ: https://t.me/addstickers/line306403106630_by_moe_sticker_bot",
  "小森めと日常スタンプ: https://t.me/addstickers/line306543762c94_by_moe_sticker_bot",
  "橘ひなの日常スタンプ: https://t.me/addstickers/line309081146e28_by_moe_sticker_bot",
  "紫宮るな日常スタンプ: https://t.me/addstickers/line30908108d247_by_moe_sticker_bot",
  "白波らむね日常スタンプ: https://t.me/addstickers/line30908109e21f_by_moe_sticker_bot",
  "紡木こかげ日常スタンプ: https://t.me/addstickers/line3091072574c5_by_moe_sticker_bot",
  "千燈ゆうひ日常スタンプ: https://t.me/addstickers/line30963876f8e3_by_moe_sticker_bot",
  "蝶屋はなび日常スタンプ: https://t.me/addstickers/line30910709b5db_by_moe_sticker_bot",
  "久々湊るい: https://t.me/addstickers/kugumirui",
  "七瀬える: https://t.me/addstickers/NanaseEru",
  "月宵あび: https://t.me/addstickers/TsukiyoiAvi_by_moe_sticker_bot",
  "涼月すい: https://t.me/addstickers/SuzutukiSui_by_moe_sticker_bot",
  "セレナーデ・オックスブラッド: https://t.me/addstickers/Serenade_Oxblood_by_moe_sticker_bot",
  "飴望にぃな: https://t.me/addstickers/amemochinina_by_moe_sticker_bot",
  "白星あわわ: https://t.me/addstickers/Awawa_by_moe_sticker_bot",
  "綿宮あひる: https://t.me/addstickers/WatamiyaAhiru_by_moe_sticker_bot",
  "海汐もるふ: https://t.me/addstickers/mishiomolf_by_moe_sticker_bot",
  "透乃おと: https://t.me/addstickers/ToonoOto_by_moe_sticker_bot",
  "紫電ライム: https://t.me/addstickers/SidenLime_by_moe_sticker_bot",
  "夜羽月みるか: https://t.me/addstickers/Youduki_Miruka_by_moe_sticker_bot",
  "綺音れむ: https://t.me/addstickers/AnonRemu_by_moe_sticker_bot",
  "Varium Line: https://t.me/addstickers/line25719061f9bf_by_moe_sticker_bot",
  "Varium: https://t.me/addstickers/varium_by_moe_sticker_bot",
  "NEUN: https://t.me/addstickers/neun_by_moe_sticker_bot",
  "MEDA: https://t.me/addstickers/meda_by_moe_sticker_bot",
  "CULUA: https://t.me/addstickers/culua_by_moe_sticker_bot",
  "天羽音みらん: https://t.me/addstickers/AmahaneMiran_by_moe_sticker_bot",
  "甘狼このみLine: https://t.me/addstickers/line2899309474f9_by_moe_sticker_bot",
  "音ノ乃のの: https://t.me/addstickers/nonononono_by_moe_sticker_bot",
  "あくび・でもんすぺーど: https://t.me/addstickers/akubi_demonspade_by_moe_sticker_bot",
  "ゆらぎゆら: https://t.me/addstickers/YuraYuragi_by_moe_sticker_bot",
  "音ノ瀬らこ: https://t.me/addstickers/OtonoseRaco_by_moe_sticker_bot",
  "ミリプロ公式LINEスタンプ @見字睇V: https://t.me/addstickers/line284400369b82_by_moe_sticker_bot",
  "天廻てん: https://t.me/addstickers/AmaeTen",
  "天廻てんTwitch: https://t.me/addstickers/amaeTenStickers_by_moe_sticker_bot",
  "にゃぷぷ: https://t.me/addstickers/Nyapupu_fsp_by_moe_sticker_bot",
  "わンころ: https://t.me/addstickers/wancoro_coro_by_moe_sticker_bot",
  "赤見かるび: https://t.me/addstickers/karubiStickers_by_moe_sticker_bot",
  "赤見かるび2: https://t.me/addstickers/karubiStickers2_by_moe_sticker_bot",
  "赤見かるび Line: https://t.me/addstickers/karubiLineStickers",
  "赤見かるび ボイススタンプ: https://t.me/addstickers/line32331b002_by_moe_sticker_bot",
  "甘城なつき Line: https://t.me/addstickers/line28887845db7d_by_moe_sticker_bot",
  "天鬼ぷるる: https://t.me/addstickers/amakipururu_by_moe_sticker_bot",
  "天鬼ぷるる Line: https://t.me/addstickers/line25781920bf4d_by_moe_sticker_bot",
  "FuwaFuwa35: https://t.me/addstickers/fuwafuwa35",
  "みたらしねこ: https://t.me/addstickers/mitachishineko",
  "久遠たま: https://t.me/addstickers/QuonTama",
  "久遠たま Line: https://t.me/addstickers/TamaLineStickers",
  "HIMEHINA: https://t.me/addstickers/HIMEHINA_sticker",
  "Kanikama: https://t.me/addstickers/KanikamaLine",
  "利香: https://t.me/addstickers/RikaChStickers",
  "みけねこ: https://t.me/addstickers/mikenekoLine",
  "麻婆豆腐: https://t.me/addstickers/line191824055a5c_by_moe_sticker_bot",
  "杏夜くもり: https://t.me/addstickers/annyakumori_by_moe_sticker_bot",
  "いぬやよ: https://t.me/addstickers/inuyayodesu_by_moe_sticker_bot",
  "いぬやよ discord: https://t.me/addstickers/inuyayodesu_discord_by_moe_sticker_bot",
  "YOSHIKA⁂: https://t.me/addstickers/yoshika_by_moe_sticker_bot",
  "ノア・ポラリス: https://t.me/addstickers/noa_polaris_by_moe_sticker_bot",
  "夢見とびら: https://t.me/addstickers/yumemitobira_by_moe_sticker_bot",
  "ペペロンチーノ: https://t.me/addstickers/line25138425f797_by_moe_sticker_bot",
  "乙夏れい: https://t.me/addstickers/otsukaray_by_moe_sticker_bot",
  "猫滅刃とばり: https://t.me/addstickers/nyahoroba_tobari_by_moe_sticker_bot",
  "人類滅亡部スタンプセット: https://t.me/addstickers/line28803852d51f_by_moe_sticker_bot",
  "領国つかさ: https://t.me/addstickers/tsukasa_ryogoku_by_moe_sticker_bot",
  "本阿弥あずさ: https://t.me/addstickers/azusa_honami_by_moe_sticker_bot",
  "王猛ちたむ: https://t.me/addstickers/chitamu_omo_by_moe_sticker_bot",
  "稍麦: https://t.me/addstickers/yayamugi_by_moe_sticker_bot",
  "稍麦Line: https://t.me/addstickers/line19981908cf70_by_moe_sticker_bot",
  "稍麦Line2: https://t.me/addstickers/line294643931430_by_moe_sticker_bot",
  "安心院みさ: https://t.me/addstickers/AnshininMisa_by_moe_sticker_bot",
  "天籠りのん: https://t.me/addstickers/LinonAmakomo_by_moe_sticker_bot",
  "凪乃ましろ: https://t.me/addstickers/line259385658fb6_by_moe_sticker_bot",
  "紫乃咲ほのあ: https://t.me/addstickers/ShinosakiHonoa_by_moe_sticker_bot",
  "タルレミ・エラ: https://t.me/addstickers/TallemiElla_by_moe_sticker_bot",
  "NoiR: https://t.me/addstickers/NoiR_by_moe_sticker_bot",
  "芽唯: https://t.me/addstickers/mei_by_moe_sticker_bot",
  "萌水団: https://t.me/addstickers/dantencho_by_moe_sticker_bot",
  "松下: https://t.me/addstickers/line254270914d85_by_moe_sticker_bot",
  "KMNZ: https://t.me/addstickers/kmnz_by_moe_sticker_bot",
  "あかつき るき: https://t.me/addstickers/AkatsukiLuci_by_moe_sticker_bot",
  "猫宮るな: https://t.me/addstickers/RunaNekomiya_by_moe_sticker_bot",
  "ミクスト公式スタンプ: https://t.me/addstickers/line31088915d73a_by_moe_sticker_bot",
  "天吹サン: https://t.me/addstickers/San_Mixstgirls_by_moe_sticker_bot",
  "雪白キャル: https://t.me/addstickers/Qalu_Mixstgirls_by_moe_sticker_bot",
  "白傘くらげ: https://t.me/addstickers/KurageShirakasa_by_moe_sticker_bot",
  "しのプロ: https://t.me/addstickers/line305600440523_by_moe_sticker_bot",
  "見字睇V: https://t.me/addstickers/SeeWordWatchV",
];

module.exports = { stickersList };
