const stickersList = [
  "35: https://t.me/addstickers/Miko_Youtube_Stickers",
  "牙衰: https://t.me/addstickers/SuiseiStickers",
  "ロボ子: https://t.me/addstickers/RobocoSan",
  "FBK: https://t.me/addstickers/shirakamiFubukiStickers",
  "Mel: https://t.me/addstickers/YozoraMelStickers",
  "牙哈: https://t.me/addstickers/AkaiHaatoStickers",
  "牙夸: https://t.me/addstickers/AquaStickers",
  "牙紫: https://t.me/addstickers/MurasakiShionStickers",
  "牙鬼: https://t.me/addstickers/AyameStickers",
  "Choco: https://t.me/addstickers/ChocoSenSeiStickers",
  "牙狗: https://t.me/addstickers/InugamiKoroneStickers",
  "牙狼: https://t.me/addstickers/ookamimioStickers",
  "牙船: https://t.me/addstickers/MarineStickers",
  "Pekora: https://t.me/addstickers/PekoraStickers",
  "牙火: https://t.me/addstickers/ShiranuiFlareStickers",
  "牙ru: https://t.me/addstickers/RushiaStickers",
  "牙猩: https://t.me/addstickers/PJKStickers",
  "牙羊: https://t.me/addstickers/WatameStickers",
  "んああああ: https://t.me/addstickers/HimemoriLunaStickers",
  "Lamy: https://t.me/addstickers/LamyStickers",
  "mmssnn: https://t.me/addstickers/NeneYoutubeStickers",
  "牙拉: https://t.me/addstickers/LaplusStickers",
  "牙沙: https://t.me/addstickers/SakamataStickers",
  "牙風: https://t.me/addstickers/kazamaYoutubeSticker",
  "牙博: https://t.me/addstickers/KoyoriStickers",
  "Gura: https://t.me/addstickers/GawrGuraYoutubeStickers",
  "IRyS https://t.me/addstickers/IRySStickers",
  "Mumei: https://t.me/addstickers/MumeiStickers",
  "Kronii: https://t.me/addstickers/KroniiStickers",
  "Bae: https://t.me/addstickers/BaelzStickers",
  "HoloEarth: https://t.me/addstickers/HoloEarthStickers",
  "Hololive Sticker Vol.1: https://t.me/addstickers/holostickerVol1",
  "Hololive Sticker Vol.2: https://t.me/addstickers/holostickerVol2",
  "Hololive ロボ子: https://t.me/addstickers/robocoLineStickers",
  "Hololive FBK Vol.2: https://t.me/addstickers/FubukiLineStickersVol2",
  "Hololive 牙夸: https://t.me/addstickers/hololiveStickerAqua",
  "Hololive 牙貓: https://t.me/addstickers/OkayuLineStamps",
  "Hololive 狼媽: https://t.me/addstickers/mioLineStickers",
  "Hololive 牙羊: https://t.me/addstickers/WatameLineStamps",
  "Hololive 牙火: https://t.me/addstickers/FlareLineStickers",
  "Hololive 牙團: https://t.me/addstickers/ShiroganeNoelStickers",
  "Hololive 菈米: https://t.me/addstickers/LamyLineStickers",
  "Hololive バカタレ: https://t.me/addstickers/bakatare",
  "郡道: https://t.me/addstickers/mirei_line_stickers1",
  "阿咩咩: https://t.me/addstickers/amamiya_animated_stickers",
  "羽衣媽媽: https://t.me/addstickers/UiShigStickers",
  "Rurudo: https://t.me/addstickers/rurudo",
  "橘ひなの: https://t.me/addstickers/HinanoStickers",
  "花芽なずな: https://t.me/addstickers/KagaNazuna",
  "兎咲ミミ: https://t.me/addstickers/TosakiStickers",
  "英リサ: https://t.me/addstickers/HanabusaStickers",
  "八雲べに: https://t.me/addstickers/YakumoBeniStickers",
  "紫宮るな: https://t.me/addstickers/shinomiyaStickers",
  "FuwaFuwa35: https://t.me/addstickers/fuwafuwa35",
  "みたらしねこ: https://t.me/addstickers/mitachishineko",
  "久遠たま: https://t.me/addstickers/QuonTama",
  "久遠たま Line: https://t.me/addstickers/TamaLineStickers",
  "利香: https://t.me/addstickers/RikaChStickers",
  "見字睇V: https://t.me/addstickers/SeeWordWatchV",
];

module.exports = { stickersList };
